<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Family;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends \Doctrine\ORM\EntityRepository
{
     // Creates a new unverified family. 
    public function createTrialFamily($data) {
        $em = $this->getEntityManager();
        $family = new Family();
        $family->setFamilyName($data['family_name']);
        $family->setCreatedOn(new \DateTime("NOW"));
        $family->setCreatedBy(0);
        $family->setModifiedOn(new \DateTime("NOW"));
        $family->setModifiedBy(0);

        $em->persist($family);
        $em->flush();

        return $family;
    }

    /**
     * This creates a URL friendly name of a family name.
     */
    private function createKey($familyName) {
        

    }
}
